---
- hosts: localhost

  vars_files:
    - vault.yaml

- name: Run with inline Compose file version 2
  hosts: localhost
  gather_facts: false
  tasks:
    - community.docker.docker_compose:
        project_src: apiway
        state: absent

    - community.docker.docker_compose:
        project_name: apiway
        definition:
          version: '2'
          services:
            db:
              image: mysql
              ports:
                - "3306:3306"
              environment: 
                - MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASS }}"
                - MYSQL_USER: "{{ MYSQL_USER }}"
                - MYSQL_PASSWORD: "{{ MYSQL_PASS }}"
                - MYSQL_DATABASE: "{{ MYSQL_DATABASE }}"
              volumes:
                - datafiles:/var/lib/mysql
                - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"  
            api:
              build: "."
              ports:
                - "5000:80"
              depends_on:
                - db
              environment: 
                - MYSQL_USER="${{ MYSQL_USER }}"
                - MYSQL_PASSWORD="${{ MYSQL_PASS }}"
            volumes:
              - data-files:
      register: output
